### ISSUE TITLE
Change font colour

### ISSUE THREAD

**Issue by sammygriffiths** [xAranaktu/FIFA-18---Career-Mode-Cheat-Table#14]
Hi, first of all thank you very much for adding the changing of kit fonts in your latest update, I like to play as lower league teams and get them promoted to the Premier League so being able to change the kit fonts to match the league is great (I also modded the sleeve badge with FrostyEditor).

However, I can't seem to find a way of editing the away kit font (and presumably the 3rd kit for teams that have one). 

As well as that, I have set the fonts to what all the other Premier League teams have but on my team it is plain white whereas the others all have the Premier League lion logo at the bottom, I believe this is because the lion is indeed there, but it is white so it blends in (of course my knowledge of editing this game is limited so I could be wrong).

It would be great if you could add those features (or alternatively let me know what I'm doing wrong if I'm simply just missing something).

Thanks.

**Comment by xAranaktu** [comment]
To edit other kits you need to edit them in the kit selection screen, like here:
![kit](https://i.imgur.com/0sXhCrz.jpg)
Dunno what font type are you using, but font type code with "lion" is 95.
Here is AS Monaco kit with Lion:
![fonttype]https://i.imgur.com/GekHsSR.jpg

Changing font colour might be tough, currently I don't have time for it.

**Comment by sammygriffiths** [comment]
Ohh that makes sense, thanks for that, I never thought to try it on the kit selection screen.

As for the numbers, I do have them set to 95 but they are plain white:
![number](https://user-images.githubusercontent.com/6638381/35481686-549fc664-0420-11e8-960d-7cb58f557fa8.jpg)

As I say, this leads me to believe that for Middlesbrough (the team I'm using) the particular colour that applies to the lion is set to white. But I totally understand that you have more important things to be doing than this and I have played for months with them in the PL with "EFL" numbers so this is definitely much better. Don't worry if you don't have time.

Thanks a lot for your help.

**Comment by xAranaktu** [comment]
Yes, you are right. Unfortunately, 95 font type does not work for me too on Middlesbrough jersey.
But still, I'm not really convinced it's font colour problem. If it would be a colour problem then championship logo shouldn't display too, we are trying to change only fonttype, so it doesn't make sense for me.

**Comment by sammygriffiths** [comment]
I believe I have determined that it is a colour problem:

I used DB Master to compare the colours of the numbers for Middlesbrough and Liverpool (as they have a similar coloured kit to Middlesbrough) and the RGB values are as follows:

```
Middlesbrough:
	Primary RGB
		220 220 220 (white)
	Secondary RGB
		12 12 12 (black)
	Tertiary RGB
		220 220 220 (white)
Liverpool:
	Primary RGB
		220 220 220 (white)
	Secondary RGB
		12 12 12 (black)
	Tertiary RGB
		12 12 12 (black)
```
As you can see the tertiary colour is different between these two teams so I guessed that must be where the lion gets its colour.

I then edited Middlesbrough's tertiary colour to match Liverpool's and imported the DB in with FrostyEditor and the numbers look as they should:
![number](https://user-images.githubusercontent.com/6638381/35488887-38fb2a86-0487-11e8-9b20-0e22c2f0af05.jpg)

But of course I unfortunately can't use this modified DB in my already existing career.

So I believe this confirms it is a colour issue. However, as I said earlier I am happy that I can at least play with the correct numbers now and I understand that you are busy so may not get to this. Thank you for your help.
