### ISSUE TITLE
Disable negotiation frequency checks

### ISSUE THREAD

**Issue by PureCS** [xAranaktu/FIFA-18---Career-Mode-Cheat-Table#15]
You are disallowed from negotiating with a player frequently, it says 'You have recently negotiated a new contract with this player'. This sometimes occurs on bugged saves as well which prevents contract negotiations. Can you please look into disabling this behaviour?

**Comment by xAranaktu** [comment]
I'll try to take a look at it tomorrow.

**Comment by xAranaktu** [comment]
https://github.com/xAranaktu/FIFA-18---Career-Mode-Cheat-Table/releases/tag/31.01.2018

**Comment by PureCS** [comment]
Works perfectly, thank you so much!
