### ISSUE TITLE
Player emotions? 

### ISSUE THREAD

**Issue by Benzalf** [xAranaktu/FIFA-18---Career-Mode-Cheat-Table#22]
Can someone explain what the player emotion  does in the edit Player Database?

**Comment by xAranaktu** [comment]
As far as I remember EA Sports introduced emotional intelligence as of the key features in fifa 15. https://www.easports.com/fifa/news/2014/fifa-15-features-emotional-intelligence
As you noticed it's stored in FIFA database, I've never tried to edit that. 
For more info you should ask this question on fifa modding forums, there are people who are making this game better for many years and maybe they will have bigger knowledge about emotions in fifa game series.

**Comment by Benzalf** [comment]
Alright. Thanks, pal.
