### ISSUE TITLE
Editing Player Wages quickly?

### ISSUE THREAD

**Issue by diaslock** [xAranaktu/FIFA-18---Career-Mode-Cheat-Table#23]
Player Contracts > Contract Negotition takes too much time. I want to edit player wages in career mode quickly. I want change all of them 20k (for example). Or i can change one by one like an editing player birthday, joindate etc.

But doing contract negotition on every players being so tiring

sorry for my bad english. Will you add this opinion?

**Comment by xAranaktu** [comment]
Added in [today's update](https://github.com/xAranaktu/FIFA-18---Career-Mode-Cheat-Table/releases/tag/12.04.2018). You can edit wages of players which are in your club by editing "wage" field in "career_playercontract Table"
