### ISSUE TITLE
women's penalty in men's league

### ISSUE THREAD

**Issue by songeda** [xAranaktu/FIFA-18---Career-Mode-Cheat-Table#31]
First of all, thank you for your work  xAranaktu :)
As you know, if a female player is in the men's league, there is a decrease in her ability.
Can you get rid of decreasing problem? If possible, please include it in the next version.
Thank you again and please reply.

**Comment by xAranaktu** [comment]
I've finished my work on this cheat table. I'll not add any new functionalities.

**Comment by songeda** [comment]
oh..I got it. Thanks.
