### ISSUE TITLE
Game crashing in "Edit Player" in career mode

### ISSUE THREAD

**Issue by davidrock** [xAranaktu/FIFA-18---Career-Mode-Cheat-Table#40]
Hi, I am unable to edit other players in other teams. When I enter in the Edit Player mode, is shown the list of players in my team, everything seems OK here, but when I try to change to another team the game is simply closing, no error code, no exception, no nothing, the game just close. I tried many version and it is still happening. The problem is I find out that Pogba and Messi are setted as Is_Retiring ON, and they are 30 years old, I did some mistake when I changed them some day, i dont know. The problem is...I can't change the teams. 
So I start in my Team, change to another team, and another and another and... POW.. game close.

**Comment by xAranaktu** [comment]
You have probably two options.
1. Attach debugger to the game process to catch unhandled exception and fix the problem.
2. Use "Editing Database"->"Database Tables"->"Players Table" to edit players.

**Comment by davidrock** [comment]
@xAranaktu thanks for your response. But I ended up unistalling the game and installing all over again, including updates 2,3,4,5 and 7. The problem doesn't happened anymore so far. Maybe was something wrong with the game itself, not related with career cheat table. I will close for now, thanks.
