### ISSUE TITLE
Manager accept chance modifier BaP

### ISSUE THREAD

**Issue by LocalBoomer** [xAranaktu/FIFA-18---Career-Mode-Cheat-Table#46]
Not sure if this is in the transfers ini but I couldn't see it so I'm requesting.

Can you give us control of the chance the manager accepts a request in Be a Pro? I wanted to start out local and watch my player move up but my team play like crippled potatoes and it's infuriating but the manager keeps rejecting my loan requests. ;_;

Thanks in advance for any responses!

**Comment by xAranaktu** [comment]
I'm not updating old FIFA cheat tables, sorry.
