### ISSUE TITLE
Unable to change kits

### ISSUE THREAD

**Issue by luckydeepankar** [xAranaktu/FIFA-18---Career-Mode-Cheat-Table#48]
Hi,
I am unable to change the kits of my team in RTG career mode. I replace the kits ID in the database editor of the kits I want with my team kits. It doesn't change the kit and resets the Kit ID. Is it something that cannot be done or am I missing something? UC Nerd said in his video that is how you're supposed to do it.
Thank you and great work!

**Comment by xAranaktu** [comment]
I don't know. I've never tried to replace kits. Ask UC Nerd. :)
