### ISSUE TITLE
Player Status

### ISSUE THREAD

**Issue by DevicsPrey** [xAranaktu/FIFA-18---Career-Mode-Cheat-Table#5]
Is it possible to change the player's status?

For example, when trying to get someone they are "Just arrived at the club" which is a lie most of the time.

I looked into the edit player list and i could only change how long was left in their contract and it didnt change the status.

Thank you

**Comment by xAranaktu** [comment]
"Editing Player" -> "Player_Data" -> "Player Info" -> edit "playerjointeamdate"
