### ISSUE TITLE
Let CPU play

### ISSUE THREAD

**Issue by RT-EB** [xAranaktu/FIFA-18---Career-Mode-Cheat-Table#6]
I remember seeing that a FIFA 17 table allowed you to let the CPU play your team in for instance Manager Career mode. You think it's possible to eventually add this in?

Cheers for all the work you've already done o/

**Comment by xAranaktu** [comment]
Idk. where you saw it, but it wasn't my table. ;p
It's probably possible, but there is very slight chance that I'll add it.

**Comment by xAranaktu** [comment]
Requested function has been added in newest update.
https://github.com/xAranaktu/FIFA-18---Career-Mode-Cheat-Table/releases/tag/20.10.2017
