### ISSUE TITLE
Can't Use Skill Moves Why????

### ISSUE THREAD

**Issue by Kingronaldo7** [xAranaktu/FIFA-18---Career-Mode-Cheat-Table#8]
Everything works. but when I enter fifa 18 game, skill doesn't work because of ???

**Comment by Kingronaldo7** [comment]
It DISABLED MY SKILL MOVES

**Comment by xAranaktu** [comment]
Did you edited player skillmoves value? You probably messed something there.

**Comment by mkerr94** [comment]
I have the same issue. I haven't touched any skill move values, only thing I can think of is I added skilled dribbling and technical dribbling traits to a player.

**Comment by mkerr94** [comment]
It appears that after a reload of the save, the issue is fixed. @Kingronaldo7 Can you confirm?
